config/routes.rb
RailsProjectHeroku::Application.routes.draw do
  resources :oks

end

app/models/ok.rb
class Ok < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/oks_controller.rb
class OksController < ApplicationController
  before_action :set_ok, only: [:show, :edit, :update, :destroy]

  # GET /oks
  # GET /oks.json
  def index
    @oks = Ok.all
  end

  # GET /oks/1
  # GET /oks/1.json
  def show
  end

  # GET /oks/new
  def new
    @ok = Ok.new
  end

  # GET /oks/1/edit
  def edit
  end

  # POST /oks
  # POST /oks.json
  def create
    @ok = Ok.new(ok_params)

    respond_to do |format|
      if @ok.save
        format.html { redirect_to @ok, notice: 'Ok was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ok }
      else
        format.html { render action: 'new' }
        format.json { render json: @ok.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oks/1
  # PATCH/PUT /oks/1.json
  def update
    respond_to do |format|
      if @ok.update(ok_params)
        format.html { redirect_to @ok, notice: 'Ok was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ok.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oks/1
  # DELETE /oks/1.json
  def destroy
    @ok.destroy
    respond_to do |format|
      format.html { redirect_to oks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ok
      @ok = Ok.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ok_params
      params.require(:ok).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oks_helper.rb
module OksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProjectHeroku</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/oks/_form.html.erb
<%= form_for(@ok) do |f| %>
  <% if @ok.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ok.errors.count, "error") %> prohibited this ok from being saved:</h2>

      <ul>
      <% @ok.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oks/edit.html.erb
<h1>Editing ok</h1>

<%= render 'form' %>

<%= link_to 'Show', @ok %> |
<%= link_to 'Back', oks_path %>

app/views/oks/index.html.erb
<h1>Listing oks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @oks.each do |ok| %>
      <tr>
        <td><%= ok.name %></td>
        <td><%= link_to 'Show', ok %></td>
        <td><%= link_to 'Edit', edit_ok_path(ok) %></td>
        <td><%= link_to 'Destroy', ok, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ok', new_ok_path %>

app/views/oks/new.html.erb
<h1>New ok</h1>

<%= render 'form' %>

<%= link_to 'Back', oks_path %>

app/views/oks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ok.name %>
</p>

<%= link_to 'Edit', edit_ok_path(@ok) %> |
<%= link_to 'Back', oks_path %>